/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "jhnifxijxoasvkxeoipw"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpobmlmeGlqeG9hc3ZreGVvaXB3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAzNTU0OTYsImV4cCI6MjA4NTkzMTQ5Nn0.u827lDpnFaS1vt-gFCron8cYZplDxsDy4-1rSuwWaBY"